$kind: http-request
name: https://petstore.swagger.io/v2/user/login?username={{username}}&password={{password}}
url: https://petstore.swagger.io/v2/user/login?username={{username}}&password={{password}}
method: GET
queryParams:
  username: "{{username}}"
  password: "{{password}}"
order: 3808617493742949
